:Author: Anhad
:Email: appdeveloperanhad@gmail.com
:Date: 12/07/2019
:Revision: 1.5
:License: MIT

= Arduino Obstacle Aboidance Car AI

Arduino Obstacle Ovidance Robot By Anhad Singh Python

== Step 1: Installation
This is a open source project. Edit and share. Created and managed By Anhad Singh Python

For example:

1. Open this file
2. Edit as you like

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 Obstacle                 => Arduino sketch folder
  ├── Obstacle.ino        => Main Arduino Ino Sketch
  ├── sketch.json         => Temp Arduino Json sketch.json File
  └── ReadMe.adoc         => Read Me file for intructions.
....

=== License
This project is released under a MIT License.

=== Contributing
To contribute to this project please contact Anhad https://fire-apps.github.io/apps

=== Help
Go to https://fire-apps.github.io/apps for more info anf help.
